# Use root/example as user/password credentials
version: '3.1'

services:
  node-express-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/user/app
    container_name: node-express-docker
    ports:
      - '4000:4000'
      - '8080:8080'
    command: npm run start
